name: "Deploy GWT"

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout GWT Tools
        uses: actions/checkout@v2
        with:
          repository: 'keeps/tools'
          path: 'gwt-tools'
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          java-package: jdk
      - name: Build with Ant
        run: |
          export GWT_TOOLS=$(pwd)/gwt-tools
          ant clean dist -Dgwt.version=2.9.0-jetty94
      - name: Deploy to GitHub packages
        run: maven/push-gwt.sh
        env:
          GWT_MAVEN_REPO_ID: github
          GWT_MAVEN_REPO_URL: https://maven.pkg.github.com/keeps/gwt
